// <auto-generated />
using System;
using LuckyWheel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuckyWheel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812074317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuckyWheel.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAtUtc");

                    b.HasIndex("AdminUserId", "CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RequiresKey")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WheelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WheelId");

                    b.ToTable("Prizes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prizes_KeyRequiresQuantity", "[RequiresKey] = 0 OR [TotalQuantity] > 0");

                            t.HasCheckConstraint("CK_Prizes_TotalQuantity", "[TotalQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.PrizeKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedSpinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodeEncrypted")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSpinId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("PrizeId", "Status", "CreatedAtUtc");

                    b.ToTable("PrizeKeys", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.PrizeRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConfirmedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PrizeKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpinId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByAdminId");

                    b.HasIndex("PrizeKeyId")
                        .IsUnique();

                    b.HasIndex("SpinId")
                        .IsUnique();

                    b.ToTable("PrizeRedemptions", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.SpinHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmailOriginal")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrizeKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("WheelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WheelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PrizeKeyId")
                        .IsUnique()
                        .HasFilter("[PrizeKeyId] IS NOT NULL");

                    b.HasIndex("ReceiptToken")
                        .IsUnique();

                    b.HasIndex("PrizeId", "CreatedAtUtc");

                    b.HasIndex("WheelVersionId", "CreatedAtUtc");

                    b.HasIndex("WheelId", "EmailNormalized", "CreatedAtUtc");

                    b.ToTable("SpinHistories", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.Wheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Wheels", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.WheelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClaimDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WheelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WheelId")
                        .IsUnique()
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("WheelId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("WheelVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WheelVersions_ClaimDuration", "[ClaimDurationMinutes] > 0");

                            t.HasCheckConstraint("CK_WheelVersions_ValidPeriod", "[EndAtUtc] > [StartAtUtc]");

                            t.HasCheckConstraint("CK_WheelVersions_VersionNumber", "[VersionNumber] > 0");
                        });
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.WheelVersionPrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsNoPrize")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProbabilityWeight")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WheelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrizeId");

                    b.HasIndex("WheelVersionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("WheelVersionId", "PrizeId");

                    b.ToTable("WheelVersionPrizes", null, t =>
                        {
                            t.HasCheckConstraint("CK_WheelVersionPrizes_DisplayOrder", "[DisplayOrder] > 0");

                            t.HasCheckConstraint("CK_WheelVersionPrizes_PrizeReference", "([IsNoPrize] = 1 AND [PrizeId] IS NULL) OR ([IsNoPrize] = 0 AND [PrizeId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_WheelVersionPrizes_ProbabilityWeight", "[ProbabilityWeight] >= 0");
                        });
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.WinnerLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrizeKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SpinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UnlockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UnlockedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WheelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrizeKeyId");

                    b.HasIndex("SpinId");

                    b.HasIndex("WheelId", "EmailNormalized")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("WinnerLocks", (string)null);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.Prize", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.Wheel", null)
                        .WithMany()
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.PrizeKey", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.SpinHistory", null)
                        .WithMany()
                        .HasForeignKey("AssignedSpinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LuckyWheel.Domain.Entities.Prize", null)
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.PrizeRedemption", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyWheel.Domain.Entities.PrizeKey", null)
                        .WithMany()
                        .HasForeignKey("PrizeKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyWheel.Domain.Entities.SpinHistory", null)
                        .WithMany()
                        .HasForeignKey("SpinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.SpinHistory", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.Prize", null)
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LuckyWheel.Domain.Entities.PrizeKey", null)
                        .WithMany()
                        .HasForeignKey("PrizeKeyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LuckyWheel.Domain.Entities.Wheel", null)
                        .WithMany()
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyWheel.Domain.Entities.WheelVersion", null)
                        .WithMany()
                        .HasForeignKey("WheelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.WheelVersion", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.Wheel", null)
                        .WithMany()
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.WheelVersionPrize", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.Prize", null)
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LuckyWheel.Domain.Entities.WheelVersion", null)
                        .WithMany()
                        .HasForeignKey("WheelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuckyWheel.Domain.Entities.WinnerLock", b =>
                {
                    b.HasOne("LuckyWheel.Domain.Entities.PrizeKey", null)
                        .WithMany()
                        .HasForeignKey("PrizeKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyWheel.Domain.Entities.SpinHistory", null)
                        .WithMany()
                        .HasForeignKey("SpinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyWheel.Domain.Entities.Wheel", null)
                        .WithMany()
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
