<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LuckyWheel.Application\LuckyWheel.Application.csproj" />
    <ProjectReference Include="..\LuckyWheel.Infrastructure\LuckyWheel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
